version: "4.10.1"


service:
  db:
    image: postgres: 12.11
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD: shimo090da

  api:
    build:
      context: ./backend/
    dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./api:/app
      - ./api/vendor/bundle:/app/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3001:3000
    depends_on:
      - db


  front:

volumes:
  postgres-data: